name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up GCC
      uses: actions/setup-gcc@v2
      with:
        gcc-version: '10'

    - name: Build
      run: |
        gcc -o my_app src/main.c src/functions.c -Iinclude

